spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# tránh oauth/jwt ?òi env
jwt.secret=test_jwt_secret
spring.security.oauth2.client.registration.google.client-id=dummy
spring.security.oauth2.client.registration.google.client-secret=dummy
