name: CI

on:
  push:
    branches: [ "develop", "main", "master", "production" ]
  pull_request:
    branches: [ "develop", "main", "master", "production" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      # Nếu repo của bạn có gradlew thì dùng gradlew (chuẩn nhất)
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Test
        run: ./gradlew test

      - name: Build bootJar
        run: ./gradlew bootJar -x test

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
